sonar.projectKey=EmritoHeltar_sopra-fs26-group-41-client
sonar.organization=emritoheltar
sonar.projectName=sopra-fs26-group-41-client
# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=./app